PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT *
WHERE {
    <$uri$> rdfs:label ?label ;
    OPTIONAL {
        <$uri$> foaf:name ?nameFoaf ;
        dbp:name ?nameDbp ;
        dbo:city ?city ;
        dbo:country ?country ;
        dbp:state ?state ;
        dbo:endowment ?endowment ;
        dbp:motto ?motto ;
        dbp:academicStaff ?academicStaff ;
        dbp:administrativeStaff ?administrativeStaff ;
        dbp:doctoral ?doctoral ;
        dbo:numberOfDoctoralStudents ?numberOfDoctoralStudents ;
        dbp:established ?established ;
        dbp:president ?president ;
        dbp:students ?students ;
        dbo:numberOfStudents ?numberOfStudents ;
        dbp:undergrad ?undergrad ;
        dbp:website ?website ;
        foaf:homepage ?homepage ;
        georss:point ?point ;
        rdfs:comment ?comment ;
        dbo:abstract ?abstract .
    }
    FILTER (lang(?label) = "fr")
    FILTER (lang(?comment) = "fr")
    FILTER (lang(?abstract) = "fr")
}
GROUP BY ?label