PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT *
WHERE {
    <$uri$> rdfs:label ?label .

    OPTIONAL { <$uri$> foaf:name ?nameFoaf . }
    OPTIONAL { <$uri$> dbp:name ?nameDbp . }
    OPTIONAL { <$uri$> dbo:city ?city .
               ?city rdfs:label ?citylabel . }
    OPTIONAL { <$uri$> dbo:location ?location .}
    OPTIONAL { <$uri$> dbo:country ?country .
               ?country dbp:commonName ?countrylabel . }
    OPTIONAL { <$uri$> dbp:state ?state . }
    OPTIONAL { <$uri$> dbo:endowment ?endowment . }
    OPTIONAL { <$uri$> dbp:motto ?motto . }
    OPTIONAL { <$uri$> dbp:academicStaff ?academicStaff . }
    OPTIONAL { <$uri$> dbp:administrativeStaff ?administrativeStaff . }
    OPTIONAL { <$uri$> dbp:doctoral ?doctoral . }
    OPTIONAL { <$uri$> dbo:numberOfDoctoralStudents ?numberOfDoctoralStudents . }
    OPTIONAL { <$uri$> dbp:established ?established . }
    OPTIONAL { <$uri$> dbp:president ?president . }
    OPTIONAL { <$uri$> dbp:students ?students . }
    OPTIONAL { <$uri$> dbo:numberOfStudents ?numberOfStudents . }
    OPTIONAL { <$uri$> dbp:undergrad ?undergrad . }
    OPTIONAL { <$uri$> dbp:website ?website . }
    OPTIONAL { <$uri$> foaf:homepage ?homepage . }
    OPTIONAL { <$uri$> georss:point ?point . }
    OPTIONAL { <$uri$> rdfs:comment ?comment . }
    OPTIONAL { <$uri$> dbo:abstract ?abstract . }


    FILTER (lang(?countrylabel) = "fr")
    FILTER (lang(?label) = "fr")
    FILTER (lang(?citylabel) = "fr")
    FILTER (lang(?comment) = "fr")
    FILTER (lang(?abstract) = "fr")
}