PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT *
WHERE {
    <$uri$>
        rdfs:label ?label ;
        dbo:city ?cityUrl .

    OPTIONAL {
        <$uri$>
            georss:point ?coordinates ;
            rdfs:comment ?comment ;
            dbp:name ?name ;
            dbo:abstract ?abstract .
    }

    ?cityUrl
        dbp:name ?cityName ;
        dbo:country ?countryUrl .

    ?countryUrl
        dbp:commonName ?countryName .

    FILTER (lang(?label) = "fr") .
    FILTER (lang(?comment) = "fr") .
    FILTER (lang(?abstract) = "fr") .
}